import type { Metadata } from "next";
import { Providers } from "../providers";
import "../../styels/global.css"; // Correct path for your global CSS

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gray-50 text-gray-900 antialiased">
        <Providers>
          <div className="flex flex-col min-h-screen">
            <main className="container mx-auto max-w-7xl flex-grow ">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
